services:
  pgdatabase:
    image: postgres:17-alpine
    container_name: pg-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./postgres_data:/var/lib/postgresql/data: rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_SERVER_JSON_FILE=./pgadmin_config/servers.json
    ports:
      - "8888:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_config:/pgadmin_config
    depends_on:
      pgdatabase:
        condition: service_started
